In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Or use a raw string (prefix 'r')
dataset = pd.read_csv(r"C:\Users\snega\Desktop\python\BIG DATA\Market_Basket_Optimisation.csv", header=None)

transactions = []
for i in range(0, 7501):
    transactions.append([str(dataset.values[i, j]) for j in range(0, 20)])

In [3]:
dataset

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Get the attribute names (column names)
attribute_names = dataset.columns

# Print or use the attribute names as needed
print("Attribute Names:", attribute_names)

Attribute Names: Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
            19],
           dtype='int64')

In [5]:
# Assuming the items you are interested in are in a specific column, let's say the first column (index 0)
column_index = 0  # Replace with the actual index of the column you are interested in
unique_items = dataset.iloc[:, column_index].unique()

# Print or use the unique items as needed
print("Unique Items:", unique_items)

Unique Items: ['shrimp' 'burgers' 'chutney' 'turkey' 'mineral water' 'low fat yogurt'
 'whole wheat pasta' 'soup' 'frozen vegetables' 'french fries' 'eggs'
 'cookies' 'spaghetti' 'meatballs' 'red wine' 'rice' 'parmesan cheese'
 'ground beef' 'sparkling water' 'herb & pepper' 'pickles' 'energy bar'
 'fresh tuna' 'escalope' 'avocado' 'tomato sauce' 'clothes accessories'
 'energy drink' 'chocolate' 'grated cheese' 'yogurt cake' 'mint'
 'asparagus' 'champagne' 'ham' 'muffins' 'french wine' 'chicken' 'pasta'
 'tomatoes' 'pancakes' 'frozen smoothie' 'carrots' 'yams' 'shallot'
 'butter' 'light mayo' 'pepper' 'candy bars' 'cooking oil' 'milk'
 'green tea' 'bug spray' 'oil' 'olive oil' 'salmon' 'cake' 'almonds'
 'salt' 'strong cheese' 'hot dogs' 'pet food' 'whole wheat rice'
 'antioxydant juice' 'honey' 'sandwich' 'salad' 'magazines' 'protein bar'
 'mayonnaise' 'cider' 'burger sauce' 'green grapes' 'vegetables mix'
 'bramble' 'nonfat milk' 'tomato juice' 'green beans' 'strawberries'
 'eggplant' 'mushroom cream sauce' 'gums' 'cereals' 'flax seed' 'spinach'
 'soda' 'dessert wine' 'corn' 'fresh bread' 'brownies' 'fromage blanc'
 'chocolate bread' 'mashed potato' 'gluten free bar' 'cottage cheese'
 'whole weat flour' 'chili' 'barbecue sauce' 'light cream'
 'mint green tea' 'black tea' 'bacon' 'shampoo' 'blueberries'
 'cauliflower' 'extra dark chocolate' 'white wine' 'babies food'
 'toothpaste' 'melons' 'ketchup' 'cream' 'hand protein bar' 'body spray'
 'oatmeal']

In [6]:
# Initialize a dictionary to store counts for each unique item
unique_items_counts = {}

# Iterate through columns and update counts
for column in dataset.columns:
    column_counts = dataset[column].value_counts().to_dict()
    
    # Update the overall counts with counts from the current column
    for item, count in column_counts.items():
        unique_items_counts[item] = unique_items_counts.get(item, 0) + count

# Convert the dictionary to a DataFrame for better presentation (optional)
unique_items_counts_df = pd.DataFrame(list(unique_items_counts.items()), columns=['Item', 'Count'])

# Print or use the counts as needed
print("Counts of Unique Items Across All Columns:")
print(unique_items_counts_df)

Counts of Unique Items Across All Columns:
                  Item  Count
0        mineral water   1788
1              burgers    654
2               turkey    469
3            chocolate   1230
4    frozen vegetables    715
..                 ...    ...
115           zucchini     71
116                tea     29
117        water spray      3
118            napkins      5
119          asparagus      1

[120 rows x 2 columns]

In [7]:
data_types = {'Column1': str, 'Column2': str, 'Column3': str}  # Replace Column1, Column2, Column3, ... with your actual column names

# Read the CSV file with specified data types
dataset = pd.read_csv(r"C:\Users\snega\Desktop\python\BIG DATA\Market_Basket_Optimisation.csv", dtype=data_types)

# Now, you can get the attribute names and their data types
attribute_info = dataset.dtypes

# Print or use the attribute information as needed
print("Attribute Information:", attribute_info)

Attribute Information: shrimp                object
almonds               object
avocado               object
vegetables mix        object
green grapes          object
whole weat flour      object
yams                  object
cottage cheese        object
energy drink          object
tomato juice          object
low fat yogurt        object
green tea             object
honey                 object
salad                 object
mineral water         object
salmon                object
antioxydant juice     object
frozen smoothie       object
spinach               object
olive oil            float64
dtype: object

In [8]:
dataset.shape

(7500, 20)

# //Convert Pandas DataFrame into a list of lists

In [9]:
for i in range(0, 7501):
    transactions.append([str(dataset.values[i,j]) for j in range(0,20)])

IndexError: index 7500 is out of bounds for axis 0 with size 7500

In [ ]:
!pip install apyori

# //Build the Apriori model
We import the apriori function from the apyori module. We store the resulting output from apriori function in the ‘rules’ variable. To the apriori function, we pass 6 parameters:

1. The transactions List as the main inputs

2. Minimum support, which we set as 0.003 We get that value by considering that a product should appear at least in 3 transactions in a day. Our data is collected over a week. Hence, the support value should be 3*7/7500 = 0.0028

3. Minimum confidence, which we choose to be 0.2 (obtained over-analyzing various results)

4. Minimum lift, which we’ve set to 3

5. Minimum Length is set to 2, as we are calculating the lift values for buying an item B given another item A is bought, so we take 2 items into consideration.

6. Minimum Length is set to 2 using the same logic[6].

In [ ]:
from apyori import apriori
rules = apriori(transactions = transactions, min_support = 0.003, min_cinfidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

# Print out the number of rules as list

In [ ]:
results = list(rules)

# Have a glance at the rules

In [ ]:
results

# Visualizing the results
In the LHS variable, we store the first item from all the results, from which we obtain the second item that is bought after that item is already bought, which is now stored in the RHS variable. The supports, confidences and lifts store all the support, confidence and lift values from the results .

In [ ]:
def inspect(results):
    lhs         =[tuple(result[2][0][0])[0] for result in results]
    rhs         =[tuple(result[2][0][1])[0] for result in results]
    supports    =[result[1] for result in results]
    confidences =[result[2][0][2] for result in results]
    lifts        =[result[2][0][3] for result in results]
    return list (zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ["Left hand side", "Right hand side", "Support", "Confidence", "Lift"])

# Finally, we store these variables into one dataframe, so that they are easier to visualize

In [ ]:
resultsinDataFrame

# This is the final result of our apriori implementation in python. The SuperMarket will use this data to boost their sales and prioritize giving offers on the pair of items with greater Lift values

In [ ]:
resultsinDataFrame.nlargest(n = 10, columns = "Lift")